# coding: utf-8
# flake8: noqa

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Car(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, license_plate=None, driver_name=None, driver_skill=None, token=None):  # noqa: E501
        """Car - a model defined in OpenAPI

        :param id: The id of this Car.  # noqa: E501
        :type id: str
        :param license_plate: The license_plate of this Car.  # noqa: E501
        :type license_plate: str
        :param driver_name: The driver_name of this Car.  # noqa: E501
        :type driver_name: str
        :param driver_skill: The driver_skill of this Car.  # noqa: E501
        :type driver_skill: str
        :param token: The token of this Car.  # noqa: E501
        :type token: str
        """
        self.openapi_types = {
            'id': str,
            'license_plate': str,
            'driver_name': str,
            'driver_skill': str,
            'token': str
        }

        self.attribute_map = {
            'id': 'id',
            'license_plate': 'license_plate',
            'driver_name': 'driver_name',
            'driver_skill': 'driver_skill',
            'token': 'token'
        }

        self._id = id
        self._license_plate = license_plate
        self._driver_name = driver_name
        self._driver_skill = driver_skill
        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'Car':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Car of this Car.  # noqa: E501
        :rtype: Car
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Car.


        :return: The id of this Car.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Car.


        :param id: The id of this Car.
        :type id: str
        """

        self._id = id

    @property
    def license_plate(self):
        """Gets the license_plate of this Car.


        :return: The license_plate of this Car.
        :rtype: str
        """
        return self._license_plate

    @license_plate.setter
    def license_plate(self, license_plate):
        """Sets the license_plate of this Car.


        :param license_plate: The license_plate of this Car.
        :type license_plate: str
        """
        if license_plate is None:
            raise ValueError("Invalid value for `license_plate`, must not be `None`")  # noqa: E501

        self._license_plate = license_plate

    @property
    def driver_name(self):
        """Gets the driver_name of this Car.


        :return: The driver_name of this Car.
        :rtype: str
        """
        return self._driver_name

    @driver_name.setter
    def driver_name(self, driver_name):
        """Sets the driver_name of this Car.


        :param driver_name: The driver_name of this Car.
        :type driver_name: str
        """
        if driver_name is None:
            raise ValueError("Invalid value for `driver_name`, must not be `None`")  # noqa: E501

        self._driver_name = driver_name

    @property
    def driver_skill(self):
        """Gets the driver_skill of this Car.


        :return: The driver_skill of this Car.
        :rtype: str
        """
        return self._driver_skill

    @driver_skill.setter
    def driver_skill(self, driver_skill):
        """Sets the driver_skill of this Car.


        :param driver_skill: The driver_skill of this Car.
        :type driver_skill: str
        """

        self._driver_skill = driver_skill

    @property
    def token(self):
        """Gets the token of this Car.


        :return: The token of this Car.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this Car.


        :param token: The token of this Car.
        :type token: str
        """

        self._token = token
