# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.car import Car
from openapi_server import util

from openapi_server.models.car import Car  # noqa: E501

class CarsList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """CarsList - a model defined in OpenAPI

        :param items: The items of this CarsList.  # noqa: E501
        :type items: List[Car]
        """
        self.openapi_types = {
            'items': List[Car]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'CarsList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CarsList of this CarsList.  # noqa: E501
        :rtype: CarsList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this CarsList.


        :return: The items of this CarsList.
        :rtype: List[Car]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this CarsList.


        :param items: The items of this CarsList.
        :type items: List[Car]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items
