# coding: utf-8
# flake8: noqa

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.car_info import CarInfo
from openapi_server import util

from openapi_server.models.car_info import CarInfo  # noqa: E501

class CarsInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """CarsInfo - a model defined in OpenAPI

        :param items: The items of this CarsInfo.  # noqa: E501
        :type items: CarInfo
        """
        self.openapi_types = {
            'items': CarInfo
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'CarsInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CarsInfo of this CarsInfo.  # noqa: E501
        :rtype: CarsInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this CarsInfo.


        :return: The items of this CarsInfo.
        :rtype: CarInfo
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this CarsInfo.


        :param items: The items of this CarsInfo.
        :type items: CarInfo
        """

        self._items = items
