# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class HALEngineer(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, links=None):  # noqa: E501
        """HALEngineer - a model defined in OpenAPI

        :param links: The links of this HALEngineer.  # noqa: E501
        :type links: object
        """
        self.openapi_types = {
            'links': object
        }

        self.attribute_map = {
            'links': '_links'
        }

        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'HALEngineer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HALEngineer of this HALEngineer.  # noqa: E501
        :rtype: HALEngineer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self):
        """Gets the links of this HALEngineer.


        :return: The links of this HALEngineer.
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this HALEngineer.


        :param links: The links of this HALEngineer.
        :type links: object
        """

        self._links = links
# flake8: noqa
