# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class HALWorkItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _self=None):  # noqa: E501
        """HALWorkItem - a model defined in OpenAPI

        :param _self: The _self of this HALWorkItem.  # noqa: E501
        :type _self: object
        """
        self.openapi_types = {
            '_self': object
        }

        self.attribute_map = {
            '_self': 'self'
        }

        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'HALWorkItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HALWorkItem of this HALWorkItem.  # noqa: E501
        :rtype: HALWorkItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self):
        """Gets the _self of this HALWorkItem.


        :return: The _self of this HALWorkItem.
        :rtype: object
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this HALWorkItem.


        :param _self: The _self of this HALWorkItem.
        :type _self: object
        """

        self.__self = _self
# flake8: noqa
