# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PlanningItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, embedded=None):  # noqa: E501
        """PlanningItem - a model defined in OpenAPI

        :param embedded: The embedded of this PlanningItem.  # noqa: E501
        :type embedded: object
        """
        self.openapi_types = {
            'embedded': object
        }

        self.attribute_map = {
            'embedded': '_embedded'
        }

        self._embedded = embedded

    @classmethod
    def from_dict(cls, dikt) -> 'PlanningItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlanningItem of this PlanningItem.  # noqa: E501
        :rtype: PlanningItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def embedded(self):
        """Gets the embedded of this PlanningItem.


        :return: The embedded of this PlanningItem.
        :rtype: object
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """Sets the embedded of this PlanningItem.


        :param embedded: The embedded of this PlanningItem.
        :type embedded: object
        """

        self._embedded = embedded
# flake8: noqa
