# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.planning_item import PlanningItem
from openapi_server import util

from openapi_server.models.planning_item import PlanningItem  # noqa: E501

class PlanningItemsList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, links=None, items=None):  # noqa: E501
        """PlanningItemsList - a model defined in OpenAPI

        :param links: The links of this PlanningItemsList.  # noqa: E501
        :type links: object
        :param items: The items of this PlanningItemsList.  # noqa: E501
        :type items: List[PlanningItem]
        """
        self.openapi_types = {
            'links': object,
            'items': List[PlanningItem]
        }

        self.attribute_map = {
            'links': '_links',
            'items': 'items'
        }

        self._links = links
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'PlanningItemsList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlanningItemsList of this PlanningItemsList.  # noqa: E501
        :rtype: PlanningItemsList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self):
        """Gets the links of this PlanningItemsList.


        :return: The links of this PlanningItemsList.
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this PlanningItemsList.


        :param links: The links of this PlanningItemsList.
        :type links: object
        """

        self._links = links

    @property
    def items(self):
        """Gets the items of this PlanningItemsList.


        :return: The items of this PlanningItemsList.
        :rtype: List[PlanningItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this PlanningItemsList.


        :param items: The items of this PlanningItemsList.
        :type items: List[PlanningItem]
        """

        self._items = items
# flake8: noqa
