# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Token(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, license=None):  # noqa: E501
        """Token - a model defined in OpenAPI

        :param id: The id of this Token.  # noqa: E501
        :type id: str
        :param license: The license of this Token.  # noqa: E501
        :type license: str
        """
        self.openapi_types = {
            'id': str,
            'license': str
        }

        self.attribute_map = {
            'id': 'id',
            'license': 'license'
        }

        self._id = id
        self._license = license

    @classmethod
    def from_dict(cls, dikt) -> 'Token':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Token of this Token.  # noqa: E501
        :rtype: Token
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Token.


        :return: The id of this Token.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Token.


        :param id: The id of this Token.
        :type id: str
        """

        self._id = id

    @property
    def license(self):
        """Gets the license of this Token.


        :return: The license of this Token.
        :rtype: str
        """
        return self._license

    @license.setter
    def license(self, license):
        """Sets the license of this Token.


        :param license: The license of this Token.
        :type license: str
        """

        self._license = license
