# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop
- master

jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.6'
    inputs:
      versionSpec: '>= 3.6'

  - script: |
      pip3 install tox
      cp config.example.py config.py
      tox
    displayName: 'Run tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: 'test-*.xml'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'cov-nosetests.xml'
      reportDirectory: 'cov-nosetests-html'
    condition: succeededOrFailed()

- job: 'Deploy'
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: 'Test'
  steps:
  - script: |
      zip -r deploy.zip .
    displayName: 'Create deployment artifact'

  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: deploy.zip
