openapi: 3.0.1
info:
  contact:
    email: opensource@vwt.digital
    name: VolkerWessels Telecom - Digital Ambition Team
    url: https://vwt-digital.github.io/
  description: Endpoint to retreive the latest car locations
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  title: snbplanningtool
  version: 1.0.0
  x-audience: company-internal
  x-api-id: e2a63575-f436-4e31-8f34-fadbad0d9693
servers:
- url: //PROJECT_ID.appspot.com/
security:
- OAuth2AzureAD:
  - snbplanningapi.read
paths:
  /cars:
    get:
      description: Get a list of all car geolocations
      operationId: cars_get
      parameters:
      - description: Time offset range in hours for retrieving entries
        in: query
        name: offset
        schema:
          default: 168
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cars'
          description: Successful response - returns an array of locations
      summary: Get car locations
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /carsinfo:
    get:
      description: Get a list of all car geolocations with info
      operationId: carsinfo_get
      parameters:
      - description: Time offset range in hours for retrieving entries
        in: query
        name: offset
        schema:
          default: 168
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarsInfo'
          description: Successful response - returns an array of locations with info
      summary: Get car info
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    Cars:
      description: Collection of Cars
      example:
        type: FeatureCollection
        features:
        - type: Feature
          geometry:
            type: Point
            coordinates:
            - 5.3
            - 52.6
          properties:
            license_plate: AA-BB-11
        - type: Feature
          geometry:
            type: Point
            coordinates:
            - 5.4
            - 52.5
          properties: {}
      properties:
        type:
          type: string
        features:
          items:
            $ref: '#/components/schemas/Car'
          type: array
      required:
      - features
      - type
      type: object
    Car:
      description: Information about a car
      example:
        type: Feature
        geometry:
          type: Point
          coordinates:
          - 5.3
          - 52.6
        properties:
          license_plate: AA-BB-11
      properties:
        geometry:
          $ref: '#/components/schemas/Geometry'
        type:
          type: string
        properties:
          properties: {}
          type: object
      required:
      - geometry
      - properties
      - type
      type: object
    Geometry:
      description: Geometry element
      example: |-
        type: "Point",
        coordinates:
          - 5.2,
          - 52.4
      properties:
        type:
          enum:
          - Point
          type: string
        coordinates:
          items:
            type: number
          type: array
      required:
      - coordinates
      - type
      type: object
    CarsInfo:
      description: Collection of Cars locations with info
      example:
        type: FeatureCollection
        features:
        - type: Feature
          geometry:
            type: Point
            coordinates:
            - 5.3
            - 52.6
          properties:
            license_plate: AA-BB-11
            driver_name: Pietje Puk
        - type: Feature
          geometry:
            type: Point
            coordinates:
            - 5.4
            - 52.5
          properties:
            license_plate: CC-DD-22
            driver_name: Daan de Wit
      properties:
        type:
          type: string
        features:
          items:
            $ref: '#/components/schemas/Car'
          type: array
      required:
      - features
      - type
      type: object
  securitySchemes:
    OAuth2AzureAD:
      description: OAuth through Azure AD
      flows:
        implicit:
          authorizationUrl: https://azuread.url
          scopes:
            snbplanningapi.read: Read access to snbplanningapi.
      type: oauth2
      x-tokenInfoFunc: openapi_server.controllers.security_controller_.info_from_OAuth2AzureAD
      x-scopeValidateFunc: connexion.decorators.security.validate_scope
