# coding: utf-8
# flake8: noqa

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.geometry import Geometry
from openapi_server import util

from openapi_server.models.geometry import Geometry  # noqa: E501

class WorkItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, administration=None, duration=None, start_timestamp=None, end_timestamp=None, l2_guid=None, employee_name=None, employee_number=None, description=None, city=None, zip=None, project_number=None, status=None, street=None, extra=None, hours_category=None, task_number=None, task_type=None, geometry=None):  # noqa: E501
        """WorkItem - a model defined in OpenAPI

        :param administration: The administration of this WorkItem.  # noqa: E501
        :type administration: str
        :param duration: The duration of this WorkItem.  # noqa: E501
        :type duration: int
        :param start_timestamp: The start_timestamp of this WorkItem.  # noqa: E501
        :type start_timestamp: datetime
        :param end_timestamp: The end_timestamp of this WorkItem.  # noqa: E501
        :type end_timestamp: datetime
        :param l2_guid: The l2_guid of this WorkItem.  # noqa: E501
        :type l2_guid: str
        :param employee_name: The employee_name of this WorkItem.  # noqa: E501
        :type employee_name: str
        :param employee_number: The employee_number of this WorkItem.  # noqa: E501
        :type employee_number: str
        :param description: The description of this WorkItem.  # noqa: E501
        :type description: str
        :param city: The city of this WorkItem.  # noqa: E501
        :type city: str
        :param zip: The zip of this WorkItem.  # noqa: E501
        :type zip: str
        :param project_number: The project_number of this WorkItem.  # noqa: E501
        :type project_number: str
        :param status: The status of this WorkItem.  # noqa: E501
        :type status: str
        :param street: The street of this WorkItem.  # noqa: E501
        :type street: str
        :param extra: The extra of this WorkItem.  # noqa: E501
        :type extra: str
        :param hours_category: The hours_category of this WorkItem.  # noqa: E501
        :type hours_category: str
        :param task_number: The task_number of this WorkItem.  # noqa: E501
        :type task_number: str
        :param task_type: The task_type of this WorkItem.  # noqa: E501
        :type task_type: str
        :param geometry: The geometry of this WorkItem.  # noqa: E501
        :type geometry: Geometry
        """
        self.openapi_types = {
            'administration': str,
            'duration': int,
            'start_timestamp': datetime,
            'end_timestamp': datetime,
            'l2_guid': str,
            'employee_name': str,
            'employee_number': str,
            'description': str,
            'city': str,
            'zip': str,
            'project_number': str,
            'status': str,
            'street': str,
            'extra': str,
            'hours_category': str,
            'task_number': str,
            'task_type': str,
            'geometry': Geometry
        }

        self.attribute_map = {
            'administration': 'administration',
            'duration': 'duration',
            'start_timestamp': 'start_timestamp',
            'end_timestamp': 'end_timestamp',
            'l2_guid': 'L2GUID',
            'employee_name': 'employee_name',
            'employee_number': 'employee_number',
            'description': 'description',
            'city': 'city',
            'zip': 'zip',
            'project_number': 'project_number',
            'status': 'status',
            'street': 'street',
            'extra': 'extra',
            'hours_category': 'hours_category',
            'task_number': 'task_number',
            'task_type': 'task_type',
            'geometry': 'geometry'
        }

        self._administration = administration
        self._duration = duration
        self._start_timestamp = start_timestamp
        self._end_timestamp = end_timestamp
        self._l2_guid = l2_guid
        self._employee_name = employee_name
        self._employee_number = employee_number
        self._description = description
        self._city = city
        self._zip = zip
        self._project_number = project_number
        self._status = status
        self._street = street
        self._extra = extra
        self._hours_category = hours_category
        self._task_number = task_number
        self._task_type = task_type
        self._geometry = geometry

    @classmethod
    def from_dict(cls, dikt) -> 'WorkItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WorkItem of this WorkItem.  # noqa: E501
        :rtype: WorkItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def administration(self):
        """Gets the administration of this WorkItem.


        :return: The administration of this WorkItem.
        :rtype: str
        """
        return self._administration

    @administration.setter
    def administration(self, administration):
        """Sets the administration of this WorkItem.


        :param administration: The administration of this WorkItem.
        :type administration: str
        """

        self._administration = administration

    @property
    def duration(self):
        """Gets the duration of this WorkItem.


        :return: The duration of this WorkItem.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this WorkItem.


        :param duration: The duration of this WorkItem.
        :type duration: int
        """

        self._duration = duration

    @property
    def start_timestamp(self):
        """Gets the start_timestamp of this WorkItem.


        :return: The start_timestamp of this WorkItem.
        :rtype: datetime
        """
        return self._start_timestamp

    @start_timestamp.setter
    def start_timestamp(self, start_timestamp):
        """Sets the start_timestamp of this WorkItem.


        :param start_timestamp: The start_timestamp of this WorkItem.
        :type start_timestamp: datetime
        """

        self._start_timestamp = start_timestamp

    @property
    def end_timestamp(self):
        """Gets the end_timestamp of this WorkItem.


        :return: The end_timestamp of this WorkItem.
        :rtype: datetime
        """
        return self._end_timestamp

    @end_timestamp.setter
    def end_timestamp(self, end_timestamp):
        """Sets the end_timestamp of this WorkItem.


        :param end_timestamp: The end_timestamp of this WorkItem.
        :type end_timestamp: datetime
        """

        self._end_timestamp = end_timestamp

    @property
    def l2_guid(self):
        """Gets the l2_guid of this WorkItem.


        :return: The l2_guid of this WorkItem.
        :rtype: str
        """
        return self._l2_guid

    @l2_guid.setter
    def l2_guid(self, l2_guid):
        """Sets the l2_guid of this WorkItem.


        :param l2_guid: The l2_guid of this WorkItem.
        :type l2_guid: str
        """

        self._l2_guid = l2_guid

    @property
    def employee_name(self):
        """Gets the employee_name of this WorkItem.


        :return: The employee_name of this WorkItem.
        :rtype: str
        """
        return self._employee_name

    @employee_name.setter
    def employee_name(self, employee_name):
        """Sets the employee_name of this WorkItem.


        :param employee_name: The employee_name of this WorkItem.
        :type employee_name: str
        """

        self._employee_name = employee_name

    @property
    def employee_number(self):
        """Gets the employee_number of this WorkItem.


        :return: The employee_number of this WorkItem.
        :rtype: str
        """
        return self._employee_number

    @employee_number.setter
    def employee_number(self, employee_number):
        """Sets the employee_number of this WorkItem.


        :param employee_number: The employee_number of this WorkItem.
        :type employee_number: str
        """

        self._employee_number = employee_number

    @property
    def description(self):
        """Gets the description of this WorkItem.


        :return: The description of this WorkItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this WorkItem.


        :param description: The description of this WorkItem.
        :type description: str
        """

        self._description = description

    @property
    def city(self):
        """Gets the city of this WorkItem.


        :return: The city of this WorkItem.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this WorkItem.


        :param city: The city of this WorkItem.
        :type city: str
        """

        self._city = city

    @property
    def zip(self):
        """Gets the zip of this WorkItem.


        :return: The zip of this WorkItem.
        :rtype: str
        """
        return self._zip

    @zip.setter
    def zip(self, zip):
        """Sets the zip of this WorkItem.


        :param zip: The zip of this WorkItem.
        :type zip: str
        """

        self._zip = zip

    @property
    def project_number(self):
        """Gets the project_number of this WorkItem.


        :return: The project_number of this WorkItem.
        :rtype: str
        """
        return self._project_number

    @project_number.setter
    def project_number(self, project_number):
        """Sets the project_number of this WorkItem.


        :param project_number: The project_number of this WorkItem.
        :type project_number: str
        """

        self._project_number = project_number

    @property
    def status(self):
        """Gets the status of this WorkItem.


        :return: The status of this WorkItem.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this WorkItem.


        :param status: The status of this WorkItem.
        :type status: str
        """

        self._status = status

    @property
    def street(self):
        """Gets the street of this WorkItem.


        :return: The street of this WorkItem.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street):
        """Sets the street of this WorkItem.


        :param street: The street of this WorkItem.
        :type street: str
        """

        self._street = street

    @property
    def extra(self):
        """Gets the extra of this WorkItem.


        :return: The extra of this WorkItem.
        :rtype: str
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this WorkItem.


        :param extra: The extra of this WorkItem.
        :type extra: str
        """

        self._extra = extra

    @property
    def hours_category(self):
        """Gets the hours_category of this WorkItem.


        :return: The hours_category of this WorkItem.
        :rtype: str
        """
        return self._hours_category

    @hours_category.setter
    def hours_category(self, hours_category):
        """Sets the hours_category of this WorkItem.


        :param hours_category: The hours_category of this WorkItem.
        :type hours_category: str
        """

        self._hours_category = hours_category

    @property
    def task_number(self):
        """Gets the task_number of this WorkItem.


        :return: The task_number of this WorkItem.
        :rtype: str
        """
        return self._task_number

    @task_number.setter
    def task_number(self, task_number):
        """Sets the task_number of this WorkItem.


        :param task_number: The task_number of this WorkItem.
        :type task_number: str
        """

        self._task_number = task_number

    @property
    def task_type(self):
        """Gets the task_type of this WorkItem.


        :return: The task_type of this WorkItem.
        :rtype: str
        """
        return self._task_type

    @task_type.setter
    def task_type(self, task_type):
        """Sets the task_type of this WorkItem.


        :param task_type: The task_type of this WorkItem.
        :type task_type: str
        """

        self._task_type = task_type

    @property
    def geometry(self):
        """Gets the geometry of this WorkItem.


        :return: The geometry of this WorkItem.
        :rtype: Geometry
        """
        return self._geometry

    @geometry.setter
    def geometry(self, geometry):
        """Sets the geometry of this WorkItem.


        :param geometry: The geometry of this WorkItem.
        :type geometry: Geometry
        """

        self._geometry = geometry
