---
swagger: '2.0'
x-zally-ignore: [101, 104, 105]
info:
  title: snbplanningtool
  description: Endpoint to retreive the latest car locations
  contact:
    name: VolkerWessels Telecom - Digital Ambition Team
    url: 'https://vwt-digital.github.io/'
    email: opensource@vwt.digital
  license:
    name: GNU GPLv3
    url: 'https://www.gnu.org/licenses/gpl.txt'
  version: 1.0.0
  x-audience: company-internal
  x-api-id: e2a63575-f436-4e31-8f34-fadbad0d9693
host: PROJECT_ID.appspot.com
produces:
  - application/json
paths:
  /cars:
    get:
      summary: Get car info
      operationId: cars_list
      description: Get a list of all cars and their driver information.
      parameters:
        - in: query
          name: offset
          type: integer
          required: false
          default: 168
          description: Time offset range in hours for retrieving entries
      responses:
        '200':
          description: Successful response - returns an array of locations with info
          schema:
            $ref: '#/definitions/Cars'
      x-openapi-router-controller: openapi_server.controllers.cars_controller
      security:
        - OAuth2AzureAD: [snbplanningapi.planner]
    post:
      summary: Post car info
      description: Post a list of all car geolocations with info
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Car'
      responses:
        '201':
          description: Successful POST
      x-openapi-router-controller: openapi_server.controllers.cars_controller
      security:
        - OAuth2AzureAD: [snbplanningapi.editor]
  /cars/locations:
    get:
      summary: Get car locations
      operationId: car_locations_list
      description: Get a list of all car geolocations, with their linked Hyrde tokens.
      parameters:
        - in: query
          name: offset
          type: integer
          required: false
          default: 168
          description: Time offset range in hours for retrieving entries
      responses:
        '200':
          description: Successful response - returns an array of locations
          schema:
            $ref: '#/definitions/CarLocations'
      x-openapi-router-controller: openapi_server.controllers.cars_controller
      security:
        - OAuth2AzureAD: [snbplanningapi.read]
  /cars/distances:
    get:
      summary: Get car distances from a point or workitem
      operationId: car_distances_list
      description: Get a list of Hyrde car tokens along with the distance and travel time from the specified point.
                   Only returns tokens linked to cars.
      parameters:
        - in: query
          name: work_item
          type: string
          required: true
          description: The workitem for which to find the nearest car locations
        - in: query
          name: offset
          type: integer
          required: false
          default: 168
          description: Time offset range in hours for retrieving entries
        - in: query
          name: sort
          type: string
          enum: [travel_time, distance]
          required: false
          default: travel_time
          description: Sort results by distance or travel time.
        - in: query
          name: limit
          type: integer
          required: false
          default: 3
          description: Total numer of distances to return.
      responses:
        '200':
          description: Successful response - returns an array of distances
          schema:
            $ref: '#/definitions/CarDistances'
      x-openapi-router-controller: openapi_server.controllers.cars_controller
      security:
        - OAuth2AzureAD: [snbplanningapi.planner]
  /tokens:
    get:
      summary: Get a list of tokens
      description: List of tokens
      operationId: list_tokens
      parameters:
        - name: "assigned"
          in: "query"
          type: boolean
          required: false
          default: false
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Tokens'
      x-openapi-router-controller: openapi_server.controllers.cars_controller
      security:
        - OAuth2AzureAD: [snbplanningapi.read]
  /workitems:
    get:
      summary: Get a list of work items
      description: List of work items
      parameters:
        - in: query
          name: active
          type: boolean
          required: false
          default: false
          description: Select only active workitems. When set to false, retrieves all workitems
      operationId: list_work_items
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/WorkItems'
      x-openapi-router-controller: openapi_server.controllers.workitems_controller
      security:
        - OAuth2AzureAD: [snbplanningapi.planner]
    x-eac-ignore: true
definitions:
  CarDistances:
    description: Collection of car distances.
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/CarDistance'
  CarDistance:
    description: Hyrde token with distance and traveltime.
    type: object
    properties:
      token:
        type: string
        description: the Hyrde car token
      distance:
        type: number
        format: decimal
        description: distance in km.
      travel_time:
        type: integer
        format: int32
        description: Estimated travel time in seconds.
    example:
      token: 'vwt/hyrde/01202321'
      distance: 5.0
      travel_time: 1200
  CarLocations:
    description: Collection of car locations.
    required:
      - type
      - features
    type: object
    properties:
      type:
        type: string
      features:
        type: array
        items:
          $ref: '#/definitions/CarLocation'
    example:
      type: FeatureCollection
      features:
        - type: Feature
          geometry:
            type: Point
            coordinates:
              - 5.3
              - 52.6
          properties:
            license_plate: AA-BB-11
        - type: Feature
          geometry:
            type: Point
            coordinates:
              - 5.4
              - 52.5
          properties: {}
  CarLocation:
    description: The location of a car.
    required:
      - type
      - geometry
      - properties
    type: object
    properties:
      geometry:
        $ref: '#/definitions/Geometry'
      type:
        type: string
      properties:
        type: object
    example:
      type: Feature
      geometry:
        type: Point
        coordinates:
          - 5.3
          - 52.6
      properties:
        id: 1
        license_plate: AA-BB-11
        driver_name: Pietje Puk
  Geometry:
    description: Geometry element
    required:
      - coordinates
      - type
    type: object
    properties:
      type:
        enum:
          - Point
      coordinates:
        type: array
        items:
          type: number
    example: |-
      type: "Point",
      coordinates:
        - 5.2,
        - 52.4
  Cars:
    properties:
      items:
        type: array
        $ref: '#/definitions/Car'
  Car:
    description: Information on a car and their driver
    example:
      - id: 123456789
        administration: Klantteam Noord
        license_plate: AB-12-CD
        driver_name: Billy Gates
        driver_skill: Metende
        token: some-token-value
    properties:
      id:
        type: string
      administration:
        type: string
      license_plate:
        type: string
      driver_name:
        type: string
      driver_skill:
        type: string
        enum: ["", null, "Metende", "Lasser", "Leerling", "Kraanmachinist", "Overig", "NLS", "Cluster"]
      driver_employee_number:
        type: string
      token:
        type: string
    required:
      - license_plate
      - driver_name
  Tokens:
    description: Collection of list with tokens
    required:
      - items
    type: object
    properties:
      items:
        type: object
  WorkItems:
    properties:
      items:
        type: array
        $ref: '#/definitions/WorkItem'
  WorkItem:
    description: Link2 work item
    properties:
      l2_guid:
        type: string
        format: uuid
      administration:
        type: string
      category:
        type: string
      task_type:
        type: string
      project:
        type: string
      status:
        type: string
      description:
        type: string
      start_timestamp:
        type: string
        format: date-time
      end_timestamp:
        type: string
        format: date-time
      last_updated:
        type: string
        format: date-time
      resolve_before_timestamp:
        type: string
        format: date-time
      city:
        type: string
      zip:
        type: string
      house:
        type: string
      street:
        type: string
      extra:
        type: string
      is_geocoded:
        type: boolean
      geometry:
        $ref: '#/definitions/Geometry'
      employee_name:
        type: string
      employee_number:
        type: string
      order_id:
        type: string
      sub_order_id:
        type: string
        format: uuid
      stagnation:
        type: boolean
securityDefinitions:
  OAuth2AzureAD:
    type: oauth2
    description: OAuth through Azure AD
    flow: accessCode
    authorizationUrl: 'https://azuread.url'
    tokenUrl: 'https://azuread.url'
    scopes:
      snbplanningapi.read: View
      snbplanningapi.planner: Planner
      snbplanningapi.editor: Editor
    x-tokenInfoFunc: openapi_server.controllers.security_controller_.info_from_OAuth2AzureAD
    x-scopeValidateFunc: connexion.decorators.security.validate_scope
